apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wordpress-svc
  name: wordpress-svc
spec:
  ports:
  - name: wordpress-svc
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31004
  selector:
    app: wordpress
  type: LoadBalancer

